### ISSUE TITLE
Support for AWS KMS

### ISSUE THREAD

**Issue by jonnystoten** [theupdateframework/tuf-on-ci#117]
It would be great to support signing keys in AWS KMS. Looking at the existing code it looks like this is already supported in securesystemslib (https://github.com/secure-systems-lab/securesystemslib/blob/b17caf3176783ee29dcd7453a92ee3fcd4aa76d4/securesystemslib/signer/_aws_signer.py), so would just be a case of updating tuf-on-ci-delegate to be able to import with the AWS key ID.

Let me know if that sounds right and I'll be happy to take a stab at the implementation!

**Comment by jku** [comment]
Yes, sounds correct:
* any Signer implementation in securesystemslib that `supports from_priv_key_uri() / import_()` should Just Work once you have the key generated
* Generating the key metadata just needs a bit of UI added in to tuf-on-ci-delegate
  * I have not used aws signer but the existing `import_()` seems to require the user running tuf-on-ci-delegate to be logged into AWS with GetPublicKey permission (much like GCPSigner)
  * For some reason `import_()` also seems to require a scheme string -- this may be something that could be fixed in securesystemslib side (I'll file an issue) but for now you'd need to ask user for both keyid and scheme

**Comment by jku** [comment]
https://github.com/secure-systems-lab/securesystemslib/issues/668

**Comment by jonnystoten** [comment]
Awesome, thanks! I'll have a look at this
