### ISSUE TITLE
strange signing result in root-signing-staging 

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf-on-ci#236]
very curious mistake in the current sigstore staging signing event: https://github.com/sigstore/root-signing-staging/pull/74

* I merged joshuas signatures (for root and targets)
* signing event says his signature over root is good but the one over targets is **not**?
* I can reproduce that by running tuf-on-ci-status when in the branch, debug log says `INFO:tuf.api.metadata:Key b78c9e4ff9048a1d9876a20f97fa1b3cb03223a0c520c7de730cfa9f5c7b77e5 failed to verify targets`

I have never seen an issue like this and have no ideas yet, will take a look tomorrow.

**Comment by jku** [comment]
Pasting my notes here for when we meet:

## First

* don't do git fetch if you haven't yet
* if you have the terminal still open, please save the contents 
* things to look at 
    ```
    git status
    git show
    git show origin/main
    git show origin/sign/targets-v7
    ```

## verifying the current status "on your end"

* manual test for current signing state (it lists your key as unsigned here)
```
root_md = Metadata.from_file("metadata/root.json")
targets_bytes = open("metadata/targets.json", "rb").read()
targets_md = Metadata.from_bytes(targets_bytes)
root_md.signed.get_verification_result("targets", targets_md.signed_bytes, targets_md.signatures)
```
* could check if re-signing works (without tuf-on-ci and without making metadata changes): https://gist.github.com/jku/6a6ebebc35c61c3ad615d8d961149f43

* could run `tuf-on-ci-sign --no-push sign/targets-v7` to see if your tuf-on-ci-sign agrees it's not correctly signed (note that --no-push expects that the local sign/targets-v7 branch can be committed to, may have to delete that branch first)

**Comment by joshuagl** [comment]
Jussi and I just did an investigation:
* We found out that the merged signature was incorrect (by using the manual test snippet, my key was listed as unsigned)
>>> root_md = Metadata.from_file("metadata/root.json")
>>> targets_bytes = open("metadata/targets.json", "rb").read()
>>> targets_md = Metadata.from_bytes(targets_bytes)
>>> root_md.signed.get_verification_result("targets", targets_md.signed_bytes, targets_md.signatures)
VerificationResult(verified=True, signed={'afd6a6ebad62a0dd091db368c1806eeb172c893c80bece1098fed116e985ba35', 'd7d2d47a3f644fc3a685bac7b39c81ed9f9cee48ff861b44fbd86b91e34e7829', '762cb22caca65de5e9b7b6baecb84ca989d337280ce6914b6440aea95769ad93'}, unsigned={'b78c9e4ff9048a1d9876a20f97fa1b3cb03223a0c520c7de730cfa9f5c7b77e5'})
* We then verified that re-signing with `tuf-on-ci-sign --no-push sign/targets-v7` produces a correct signature
>>> root_md.signed.get_verification_result("targets", targets_md.signed_bytes, targets_md.signatures)
VerificationResult(verified=True, signed={'b78c9e4ff9048a1d9876a20f97fa1b3cb03223a0c520c7de730cfa9f5c7b77e5', 'afd6a6ebad62a0dd091db368c1806eeb172c893c80bece1098fed116e985ba35', 'd7d2d47a3f644fc3a685bac7b39c81ed9f9cee48ff861b44fbd86b91e34e7829', '762cb22caca65de5e9b7b6baecb84ca989d337280ce6914b6440aea95769ad93'}, unsigned=set())
* So, I re-ran with push enabled to update the signing event https://github.com/sigstore/root-signing-staging/pull/82

We aren't entirely certain _how_ I was able to produce an invalid signature. Jussi suggested adding a post-signing signature verification step to the tool, so that we don't push garbage signatures in future.

**Comment by jku** [comment]
> Jussi suggested adding a post-signing signature verification step to the tool, so that we don't push garbage signatures in future.

I'll use this issue to add that (clearly missing) feature.

There is another related one #66 but I believe verifying signatures is priority one.
